# Generated by Django 5.0.6 on 2024-06-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_post_image_alter_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='header_image',
        ),
    ]
