# Generated by Django 5.0.6 on 2024-06-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_url',
        ),
    ]
